POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "MMA",
    "author": "Alex Pereira",
    "url": "https://UFC.com",
    "likes": 50,
    "user": "67a6530630bae20b47f6a426"
}