POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNEb3Jzc2VycyIsImlkIjoiNjdhNjY5OGY0MmM4OTk3NDkzYzA2ODUxIiwiaWF0IjoxNzM4OTY2MDE4fQ.z2W00DVwKa9PV2KKPbbcLnq04YuH7xI1bo4vEJjLGYs

{
    "likes": 20,
    "title": "Hockey",
    "author": "Stephen D",
    "url": "https://hockey.com",
    "user": "61" 
}